---
- name: "update packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove unneeded packages"
  become: yes
  apt:
    autoremove: yes

- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Unzip backend files"
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend
