# version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.2.0
  kubernetes: circleci/kubernetes@0.3.0

jobs:
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Build the backend"
          command: |
            cd backend
            npm install
      - save_cache:
          paths: [backend/node_modules]
          key: "backend-build"
  lint-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: ["backend-build"]
      - run:
          name: "Lint the backend"
          command: |
            cd backend
            npm install
            npm run lint
  build-and-push-docker-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            cd backend
            docker build -t adenijiayocharles/udadnodeapp:${CIRCLE_SHA1} .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push adenijiayocharles/udadnodeapp:${CIRCLE_SHA1}
  deploy-application:
    executor: aws-eks/python3
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: vhvghvgf
          install-kubectl: true
          aws-region: eu-west-2
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/deployment.yaml"
          get-rollout-status: true
          resource-name: deployment/demoapp
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/service.yaml"
  test-application:
    executor: aws-eks/python3
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: vhvghvgf
          install-kubectl: true
          aws-region: eu-west-2
      - run:
          name: Wait for service to be ready
          command: |
            kubectl get pods
            kubectl get services
            sleep 30
            for attempt in {1..20}; do
              EXTERNAL_IP=$(kubectl get service demoapp | awk '{print $4}' | tail -n1)
              echo "Checking external IP: ${EXTERNAL_IP}"
              if [ -n "${EXTERNAL_IP}" ] && [ -z $(echo "${EXTERNAL_IP}" | grep "pending") ]; then
                break
              fi
              echo "Waiting for external IP to be ready: ${EXTERNAL_IP}"
              sleep 10
            done
            sleep 180
            curl -s --retry 10 "http://$EXTERNAL_IP/health_check"
workflows:
  default:
    jobs:
      - build-backend
      - lint-backend:
          requires: [build-backend]
      - build-and-push-docker-image:
          requires: [lint-backend]
      - deploy-application:
          requires: [build-and-push-docker-image]
      - test-application:
          requires: [deploy-application]
