apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitynodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacitynodejs
  template:
    metadata:
      labels:
        app: udacitynodejs
    spec:
      containers:
        - name: udacitynodejs
          image: adenijiayocharles/udacitynodejs:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: udacitynodejs
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: udacitynodejs
