apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: app
          image: adenijiayocharles/udadnodeapp:${CIRCLE_SHA1}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
