apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: app
          image: adenijiayocharles/udanodeapp:${CIRCLE_SHA1}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  labels:
    app: demo
spec:
  # automatically create an external load-balanced IP for the service.
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: demo
