apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: udacity-capstone-app
          image: 912377934520.dkr.ecr.us-east-1.amazonaws.com/udacitycapstoneappnew:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-app-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 8080
