---
- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Unzip backend files"
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend
