---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - create_containers: 1
    - default_container_name: docker
    - default_container_image: ubuntu
    - default_container_command: sleep 1d
  roles:
    - docker
